name: macro_state
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.5.0-152'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  macros: ^0.1.0-main
  rxdart: ^0.27.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  _fe_analyzer_shared: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
